### ISSUE TITLE
Multi-class test cfg

### ISSUE THREAD

**Issue by ruchaa01** [quangnhat185/Machine_learning_projects#7]
I am trying to detect 2 classes. In this case, what changes do I need to make to my yolo_custom_test.cfg file?

**Comment by quangnhat185** [comment]
Hello @ruchaa01,

Please refer to my article [here](https://medium.com/@quangnhatnguyenle/how-to-train-yolov3-on-google-colab-to-detect-custom-objects-e-g-gun-detection-d3a1ee43eda1).

**Comment by ruchaa01** [comment]
The article gives detailed information about train file but not test file for 2 classes.

**Comment by quangnhat185** [comment]
Hey ruchaa, I think you skip this part for the article:

**Comment by quangnhat185** [comment]
Hey @ruchaa01.
I guess you skip this part from the article.  To train with more than 2 classes, you will need to change the yolov3.cfg file and label file.

`In here we apply this formula: (filters = (classes + 5)*3) to calculate the number of filters. For example, if you need to detect 2 objects, then your filter wil be: filters=(2+5)*3 = 21 and classes = 2.`

I am working on YOLOv4 at the moment, and since many people has problem with cfg configuration, I have written a script that automate all of these steps in the upcoming tutorial with YOLOv4  (maybe next week). It will be much much easier to train your custom dataset then, so stay tune

**Comment by ruchaa01** [comment]
Great , thank you so much. Looking forward for it. Will you be posting on Medium? Also, The one that you stated was for train cfg right? I will take a look again though. Thank you so much for your help.

**Comment by quangnhat185** [comment]
Hi @ruchaa01, my new tutorial for training YOLOv4 is on. You can use [this link to access it](https://medium.com/@quangnhatnguyenle/yolov4-in-google-colab-train-your-custom-dataset-traffic-signs-with-ease-3243ca91c81d?source=friends_link&sk=9278821f02e9d1921649fd261ee56683). 

Let me know if you face any problems while following it. Happy training!
